[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install --include=dev && npm run build"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 